import { PROBLEM_REASONS } from "@/domain/food/analyzeTypes";
import { MEAL_TYPES, PORTION_SIZES, PORTION_UNITS } from "@/domain/food/types";
import { PHOTO_BODY_REASONS } from "./client/problemActions";

/** The edit errors the form can show, one message each (`EditErrorCode` of the domain). */
export const EDIT_ERROR_CODES = [
  "no_items",
  "too_many_items",
  "name_too_long",
  "amount_invalid",
  "unit_missing",
  "meal_type_invalid",
  "time_invalid",
  "time_future",
  "time_too_old",
  "not_saved",
] as const;

const leaves = (prefix: string, names: readonly string[]) => names.map((name) => `${prefix}.${name}`);

/**
 * The copy the food screens read, as dotted keys from the catalog root. This is the contract with whoever
 * renders them: food.messages.test.ts demands every key in he.json and en.json. The problem panels, units,
 * meal types and sizes come from the domain lists, so a new reason or unit cannot ship without its words.
 */
export const FOOD_MESSAGE_KEYS: readonly string[] = [
  "report.sheet.note",
  "food.meta.title",
  "food.common.back",
  ...leaves("food.chooser", ["title", "lead", "photo", "photoHint", "text", "textHint", "photoOff"]),
  ...leaves("food.resume", ["title", "body", "continue", "discard"]),
  ...leaves("food.photo", [
    "title",
    "take",
    "choose",
    "hint",
    "cameraHelp",
    "noteLabel",
    "notePlaceholder",
    "preparing",
    "ready",
    "previewAlt",
    "another",
    "send",
    "unreadable",
    "offline",
  ]),
  ...leaves("food.photoUnavailable", ["title", "body", "writeInstead"]),
  ...leaves("food.text", [
    "title",
    "placeholder",
    "hint",
    "send",
    "sendManual",
    "manualNote",
    "empty",
    "draftRestored",
    "offline",
  ]),
  ...leaves("food.processing", ["title", "slow", "slowText", "cancel", "cancelled"]),
  ...PROBLEM_REASONS.flatMap((reason) => [`food.problem.${reason}.title`, `food.problem.${reason}.body`]),
  ...PHOTO_BODY_REASONS.map((reason) => `food.problem.${reason}.bodyPhoto`),
  ...leaves("food.problem.action", ["retry", "writeInstead", "saveAsWritten", "checkPending", "goHome", "signIn"]),
  ...leaves("food.quiet", ["title", "body", "cta"]),
  ...leaves("food.unavailable", ["title", "body"]),
  ...leaves("food.confirm", [
    "title",
    "titleManual",
    "manualNote",
    "fakeNote",
    "refreshed",
    "notSaved",
    "maybe",
    "estimateNote",
    "unclearTitle",
    "unclearHint",
    "when",
    "whenOther",
    "fix",
    "save",
    "saving",
    "notNow",
  ]),
  ...leaves("food.mealType", MEAL_TYPES),
  ...leaves("food.day", ["today", "yesterday"]),
  ...leaves("food.portion.size", PORTION_SIZES),
  ...leaves("food.portion", ["about", "half"]),
  ...leaves("food.unit", PORTION_UNITS),
  ...leaves("food.unitOne", PORTION_UNITS),
  ...leaves("food.edit", [
    "title",
    "lead",
    "foodLabel",
    "portion",
    "portionNone",
    "portionAmount",
    "amount",
    "unit",
    "unitChoose",
    "remove",
    "removeFor",
    "add",
    "mealType",
    "day",
    "time",
    "save",
    "saving",
    "cancel",
    "errorsTitle",
  ]),
  ...leaves("food.edit.errors", EDIT_ERROR_CODES),
  ...leaves("food.saved", ["title", "body", "first", "back"]),
];
