// Connects the app to the LOCAL Supabase stack and creates a local dev user.
//
//   1. npm run local:start    (Docker Desktop must be running)
//   2. npm run local:setup    (this script)
//   3. npm run dev
//
// It writes app/.env.local (gitignored) from `supabase status`, keeps any other value already
// in that file, generates local-only secrets, and creates (or resets) the dev user.
// The dev credentials below are for a database that exists only on this machine.
import { randomBytes } from "node:crypto";
import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import webpush from "web-push";

const ENV_PATH = ".env.local";
const DEFAULT_DEV_EMAIL = "dev@eating-coach.test";
const DEFAULT_DEV_PASSWORD = "eating-coach-local";

function readEnvFile() {
  const values = new Map();
  if (!existsSync(ENV_PATH)) return values;
  for (const line of readFileSync(ENV_PATH, "utf8").split(/\r?\n/)) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match) values.set(match[1], match[2]);
  }
  return values;
}

function localStatus() {
  try {
    return JSON.parse(execSync("npx supabase status -o json", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }));
  } catch {
    console.error("Could not read the local Supabase status. Is Docker Desktop running? Start it with: npm run local:start");
    process.exit(1);
  }
}

const status = localStatus();
const apiUrl = status.API_URL;
const publishableKey = status.PUBLISHABLE_KEY ?? status.ANON_KEY;
const secretKey = status.SECRET_KEY ?? status.SERVICE_ROLE_KEY;
if (!apiUrl || !publishableKey || !secretKey) {
  console.error("`supabase status` did not return the API URL and keys. Run: npm run local:start");
  process.exit(1);
}

// Existing values win for things that should stay stable between runs.
const env = readEnvFile();
const keep = (key, make) => env.get(key) || make();
let vapid;
const vapidKeys = () => (vapid ??= webpush.generateVAPIDKeys());

env.set("NEXT_PUBLIC_SUPABASE_URL", apiUrl);
env.set("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", publishableKey);
env.set("SUPABASE_SECRET_KEY", secretKey);
env.set("CRON_SECRET", keep("CRON_SECRET", () => randomBytes(32).toString("hex")));
env.set("NEXT_PUBLIC_VAPID_PUBLIC_KEY", keep("NEXT_PUBLIC_VAPID_PUBLIC_KEY", () => vapidKeys().publicKey));
env.set("VAPID_PRIVATE_KEY", keep("VAPID_PRIVATE_KEY", () => vapidKeys().privateKey));
env.set("VAPID_SUBJECT", keep("VAPID_SUBJECT", () => "mailto:dev@example.test"));
env.set("LOCAL_DEV_EMAIL", keep("LOCAL_DEV_EMAIL", () => DEFAULT_DEV_EMAIL));
env.set("LOCAL_DEV_PASSWORD", keep("LOCAL_DEV_PASSWORD", () => DEFAULT_DEV_PASSWORD));

const header = "# Generated by `npm run local:setup` for the LOCAL Supabase stack. Gitignored. Safe to delete and regenerate.\n";
writeFileSync(ENV_PATH, header + [...env].map(([k, v]) => `${k}=${v}`).join("\n") + "\n");

// --- local dev user (Auth admin API) ---
// New-style secret keys (sb_secret_...) go in `apikey` only; legacy JWT keys also go in Authorization.
const headers = { "content-type": "application/json", apikey: secretKey };
if (secretKey.startsWith("eyJ")) headers.authorization = `Bearer ${secretKey}`;

const email = env.get("LOCAL_DEV_EMAIL");
const password = env.get("LOCAL_DEV_PASSWORD");

async function ensureDevUser() {
  const created = await fetch(`${apiUrl}/auth/v1/admin/users`, {
    method: "POST",
    headers,
    body: JSON.stringify({ email, password, email_confirm: true }),
  });
  if (created.ok) return "created";

  const body = await created.json().catch(() => ({}));
  if (created.status !== 422 && body.error_code !== "email_exists") {
    throw new Error(`Could not create the dev user (${created.status}): ${body.msg ?? body.message ?? "unknown error"}`);
  }

  // Already there: make sure the password matches the one in .env.local.
  const list = await fetch(`${apiUrl}/auth/v1/admin/users?per_page=200`, { headers });
  const { users = [] } = await list.json();
  const existing = users.find((u) => u.email === email);
  if (!existing) throw new Error("The dev user exists but could not be found to reset its password.");
  const updated = await fetch(`${apiUrl}/auth/v1/admin/users/${existing.id}`, {
    method: "PUT",
    headers,
    body: JSON.stringify({ password, email_confirm: true }),
  });
  if (!updated.ok) throw new Error(`Could not reset the dev user's password (${updated.status}).`);
  return "already existed (password reset)";
}

const result = await ensureDevUser();
console.log(`wrote ${ENV_PATH}`);
console.log(`dev user ${email}: ${result}`);
console.log(`sign in with the LOCAL_DEV_PASSWORD value in ${ENV_PATH}`);
console.log(`Studio (local dashboard): ${status.STUDIO_URL}`);
console.log(`Mailpit (local inbox):    ${status.MAILPIT_URL ?? status.INBUCKET_URL}`);
